// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz-examples/bizdemo/hertz_gorm/biz/dal"
	"github.com/cloudwego/hertz-examples/bizdemo/hertz_gorm/biz/llm"
	"github.com/cloudwego/hertz-examples/bizdemo/hertz_gorm/biz/service"
	"github.com/cloudwego/hertz-examples/bizdemo/hertz_gorm/log"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()
	register(h)
	Init()
	h.Spin()
}

func Init() {
	dal.Init()
	log.Init()
	service.Init()
	llm.Init()
}
