// Code generated by hertz generator.

package translator

import (
	"context"

	translator "github.com/cloudwego/hertz-examples/bizdemo/hertz_gorm/biz/hertz_gen/translator"

	"github.com/cloudwego/hertz/pkg/app"
)

// TranslateText .
// @router /v1/translate [GET]
func TranslateText(ctx context.Context, c *app.RequestContext) {
	var err error
	var req translator.TranslateRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(translator.TranslateResponse)
	resp.Translation = req.Text + "翻译"

	c.JSON(200, resp)
}
