// Code generated by hertz generator.

package translator

import (
	"context"

	translator "github.com/cloudwego/hertz-examples/bizdemo/hertz_gorm/biz/hertz_gen/translator"
	"github.com/cloudwego/hertz-examples/bizdemo/hertz_gorm/biz/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

// TranslateText .
// @router /v1/translate [GET]
func TranslateText(ctx context.Context, c *app.RequestContext) {
	hlog.CtxInfof(ctx, "Received translate request: %s", c.Request.Body())
	var err error
	var req translator.TranslateRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	// 记录查询记录
	_ = service.CreateQueryRecord(ctx, req.Text, c.ClientIP(), string(c.UserAgent()))

	// 翻译
	resp, err := service.Translate(ctx, req)
	if err != nil {
		c.String(500, err.Error())
		return
	}
	c.JSON(200, resp)
}
