// Code generated by hertz generator.

package Translator

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _translatetextMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _completeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ducksayMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _synonymsMw() []app.HandlerFunc {
	// your code...
	return nil
}
