CREATE TABLE IF NOT EXISTS query_records (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    word TEXT NOT NULL,
    ip_address TEXT,
    user_agent TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;